### ISSUE TITLE
Enhancement: Field map superposition

### ISSUE THREAD

**Issue by wdconinc** [KATRIN-Experiment/Kassiopeia#39]
For our application (BL3 at NIST) we are drawn to Kassiopeia because it allows 'easy' re-calculation of our various electrostatic field configurations, while our magnetic configuration is constant but affected by ferromagnetic elements. We are therefore using the KEMField `magnetic_fieldmap` functionality with COMSOL maps as input (through intermediate vti files).

There is one issue with this field map approach. We have multiple (_n_) magnetic field maps, each defined in a separate rectangular region of space. We use a `magnetic_superposition_field` to add them all together. However, this means that for every step we get _n_-1 warnings about points outside the map range of validity
```
[KEMFIELD NORMAL MESSAGE] WARNING: could not compute magnetic field at sample point 
<KPosition>
    <0>(double)-0.00917457<\0>
    <1>(double)0.135839<\1>
    <2>(double)1.29193<\2>
<\KPosition>
```
For now we just disable this warning in the code. A next improvement would be to be able to control the verbosity of the KEMField output, which may be in the works.

Fundamentally, there may be another solution needed here. I'm thinking of implementing the following:
- include a `magnetic_fieldmap` field `outside_bounds_action` which can be any logging type (`normal`, `warning`, `error`), default would be `normal`,
- include a `magnetic_superposition_field` field `require_all` which can `true` or `false`, default to `true`.

Thoughts?

**Comment by zykure** [comment]
In principle I don't see any issue with this. The `require_all` option would certainly be useful when combining multiple field sources, not just for the field map.

For your issue with the warnings, there may be another solution.
* Instead of modifying the warning in the `KMagnetostaticFieldmap` class, one could implement a `KMagneticField::Check()` method that first checks if a field value can be computed at the given position. In `KMagnetostaticFieldmap` this would be reimplemented to check if the field map contains a value at that position.
* Then if the check method of any of the superimposed fields returns false, a single warning/error could be issued from inside `KMagneticSuperpositionField` depending on the setting of `require_all`. This could be a more versatile solution that could be further extended in future, and wouldn't be limited to the warning issue. Any thoughts?

**Comment by wdconinc** [comment]
Merged as https://github.com/KATRIN-Experiment/Kassiopeia/pull/46
