### ISSUE TITLE
Enhancement: Calculating gradients from mapped fields

### ISSUE THREAD

**Issue by wdconinc** [KATRIN-Experiment/Kassiopeia#42]
In mapped fields (e.g. KMagnetostaticFieldmap) the values of the field and gradient can be calculated from the values of the field and gradient at the grid points, respectively. The gradient, in particular, seems needed for some adiabatic trajectory calculations. The gradient could also be calculated from the values of the field at the grid points (probably to less than the equivalent order, e.g. bilinear gradient for trilinear field, bicubic for tricubic field, or so), but this is not currently implemented.

Use case: We are interested in long-duration equilibrium simulations with adiabatic trajectories in a field configuration for which we only have a mapped description (due to the presence of a ferromagnetic yoke). We are also limited to using maps of the magnetic field, without any gradient information present. Two questions arise:
- Can we calculate the field gradients from the mapped field values?
- Will adiabaticity be maintained at all when using interpolated fields and gradients?
- If not, can the interpolated field gradient be used to 'improve' adiabaticity?

As you know, I'm happy to implement stuff, but in this case I'm not sure it's going to be a solution to the use case we're encountering. Thoughts?

**Comment by zykure** [comment]
This sounds like a good idea in general. It would remove the need of providing both field and gradient values in the field maps. 

> Can we calculate the field gradients from the mapped field values?

As you said, it shouldn't be hard to implement a second interpolation stage that calculates gradient values on-the-fly, and the calculation still would be pretty fast too (just like the interpolated fields.) So there's not really a downside to this, except maybe a loss in precision that can be investigated.

As for the implementation, am I missing a reason for using a one-order-less interpolation for the gradient? The linear/cubic interpolation already computes derivatives that are used to determine the field value. Couldn't these be used directly for the gradient? In other words, isn't the gradient already being computed essentially? In the fieldmap we use the "convolution" algorithm which doesn't calculate derivatives explicitly, but it is more clear from looking at the "classic" linear/cubic algorithm.

> Will adiabaticity be maintained at all when using interpolated fields and gradients?

From my experience, the problem with adiabaticity violation is usually too steep field gradients or field discontinuities that cause problems with the integration over each step. With interpolated fields/gradients this should be less of an issue, because interpolation tends to smooth out any discontinuities. There could be some loss of precision due to this smoothing, but that can probably be mitigated by a finer resolution of the field map.

> If not, can the interpolated field gradient be used to 'improve' adiabaticity?

I don't understand this question. Could you elaborate, or did I already answer it in my reply above?

**Comment by wdconinc** [comment]
> I don't understand this question. Could you elaborate, or did I already answer it in my reply above?

Having looked into the trajectory classes in more detail since then, I realize now that that comment was nonsensical :-)

**Comment by wdconinc** [comment]
> As for the implementation, am I missing a reason for using a one-order-less interpolation for the gradient? The linear/cubic interpolation already computes derivatives that are used to determine the field value. Couldn't these be used directly for the gradient? In other words, isn't the gradient already being computed essentially? In the fieldmap we use the "convolution" algorithm which doesn't calculate derivatives explicitly, but it is more clear from looking at the "classic" linear/cubic algorithm.

Here's how my thinking was going for this. At first I was thinking of indeed reusing the linear and cubic interpolation for numeric (finite difference) gradients on the same grid points.

1. Upon opening we can just calculate the magnetic gradient to whatever order using for example a five point stencil in each dimension for all except the outer two points in the fieldmap. That would be a large upfront calculation when it would potentially not be necessary for many regions.
2. The other option I considered, therefore, is indeed to calculate the magnetic gradient on-the-fly. This would lead to reading many more points, though. To calculate the gradient in x at the (-1,-1,-1) corner to second order in the cubic interpolation, we'd need to read all the way to (-3,-1,-1). Instead of 64 field grid points, we'd need to read 156 field grid points.
3. So I started thinking about a third option where we just limit our gradient calculation to the 64 original field values and apply an interpolation of 1 order less. The 64 field values could give 27 gradients at the center of cubes e.g. based on the 8 corners of the little cube with diagonal (-1,-1,-1)-(0,0,0) we can calculate the gradients at (-0.5,-0.5,-0.5). We would then use those to linearly interpolate in the (0,0,0)-(1,1,1) cube. That is where the "one order less" statement came from.
4. Finally, it seems that there should exist a 'simple' cubic convolution expression that results in the interpolated gradient, but I feel that this should not be possible at the same order when using only the same set of grid points... This would of course be the cleanest implementation.

**Comment by wdconinc** [comment]
Merged as https://github.com/KATRIN-Experiment/Kassiopeia/pull/48
