### ISSUE TITLE
Support for extruded_poly_loop_surface as an electromagnet

### ISSUE THREAD

**Issue by JohnRabaey** [KATRIN-Experiment/Kassiopeia#50]
In our application (beam transport for a tabletop electron accelerator) we are interested in simulating the magnetic field due to a square coil. 
I think this should be possible with an `extruded_poly_loop_surface` and the integrating_field_solver. However, when I attempt to apply the magnetic field to the `extruded_poly_loop_surface`, I get a ```"WARNING:electromagnet field solver <electromagnet_field> has zero surface or space elements."```
I substituted another surface (the `cylinder_surface` used in examples) for the `extruded_poly_loop_surface`, and I didn't get the same warning, so I'm assuming this is an issue with support for `extruded_poly_loop_surface` as an electromagnet. Is adding this feature a possibility? Or could you please direct me to another solution to the problem?

**Comment by zykure** [comment]
Dear John, thanks for your interest in our software! I'm happy to provide some help and advice.

The setup you tried getting to work makes sense, but unfortunately KEMField does not allow this kind of geometry to be used for magnetic fields. In fact, it only supports 3 geometric shapes due to the implementation of the field solver: cylinder tubes (coils), cylinder surfaces (solenoids), and rods (line currents). You can see the supported shapes and their conversion to magnet elements here:

https://github.com/KATRIN-Experiment/Kassiopeia/tree/main/KEMField/Source/Interface/KGeoBag/src/KGElectromagnetConverter.cc

I think it would be possible to extend this to a rectangular shape, but of course this requires some modifications of the code. The most critical parts are the interface to the KGeoBag module where the shapes are defined, and the field solver for this type of geometry. On the other hand, it probably wouldn't be too hard to do and could be worth the effort. You can find the existing magnetic field solvers/integrators here:

https://github.com/KATRIN-Experiment/Kassiopeia/tree/main/KEMField/Source/ExternalFields/Electromagnets/src

---

Another possibility that would not require any code changes is to use the "line currents" shape, by piecing together the rectangular coil from linear segments. We're using this option at KATRIN to implement dipole coils in our beam line. The field solver in this case is rather slow compared to coils/solenoids, because each line segment is processed individually. 

The geometry must be implemented as "rod_space" in this case. You can find an example here:

https://katrin-experiment.github.io/Kassiopeia/kgeobag_complex.html#rod-space

**Comment by JohnRabaey** [comment]
Thank you for helping! 
"rod_space" does exactly what we need. It's a bummer that geometry doesn't play nicely with visualizations, but I used "rod_surface" to visualize and that worked fine.  
May I suggest adding a note about which geometries can be used for magnetic fields to the docs under `Configuring your own simulation` -> `Fields` -> `Magnetic`? I am happy to draft the change note myself and put in a pull request, if you think it's a good idea.

**Comment by zykure** [comment]
I'm glad it works for you! Updating the docs is a great idea, so just go ahead with adding that information. I've been working on the user guide recently and added some missing details, and this is something I've overlooked so far.

The visualization with rod_space should be working in principle because it is essentially the same. There is probably just the interface missing. I will have a look if I find some time. Using rod_surface instead is a good workaround though!

**Comment by JohnRabaey** [comment]
Awesome. I found the gh-pages branch, but I am new to sphinx. Should I just make the change 
on the gh-pages branch in `source/configuration.rst` and push, and then let you do the sphinx build workflow part to publish it?

**Comment by zykure** [comment]
Yes, that works for me! I'll look at your pull request and update the sphinx pages after merging. Thanks for working on this!

(FYI: There's a Makefile that has targets `html` and `github` to create the website files. This needs Sphinx and probably some plugins/themes installed.)
